number_of_critical_tasks: 2
number_of_replicas: 2
min_num_comms: 6 
max_num_comms: 6 # Due to the number of critical tasks and replicas, max possible is 6
max_comm_chain: 3
non_critical_comm: false
critical_comm: true